### ISSUE TITLE
No fingerprints working on some devices

### ISSUE THREAD

**Issue by alexyo02** [TheFreeman193/PIFS#14] opened 2024-01-27 15:46 UTC
(Original title: _None of these fingerprints work anymore_)

I used this beautiful tool together with Chiteroman's fix and at some stage it worked fine, but after the working fingerprint was banned... I tried A LOT of times to find a fingerprint that passed both Basic and Device, (I tried for hours) but none of them seem to work anymore, I tell you this just for information purposes, I can't help much... Are there other known solutions? Or are you planning something? Thank you anyway

**Comment by localh0rzd** [comment] 2024-01-27 16:10
Same issue starting today, even old known-good prints don't work anymore. However, using the same print that used to work on my primary phone still works on the secondary phone using the same PlayIntegrityFix version.

**Comment by terlynn4** [comment] 2024-01-28 02:21
If you're running a custom kernel and this issue started on/after Jan 25, that's likely causing the problem, not the FP. See https://github.com/chiteroman/PlayIntegrityFix/issues/236

**Comment by alexyo02** [comment] 2024-01-28 09:21
Thank you, I am actually running a LineageOS Kernel, I'll see if the next OTA update changes something

**Comment by TheFreeman193** [comment] 2024-01-28 12:08
Hi there. Testing on my own device I can see there are still a good number that pass DEVICE in the collection. I suspect the failure is related to recent changes to DroidGuard and the bytecode it downloads/runs.

Are you passing BASIC with all the prints you're trying, or always getting no labels/NO_INTEGRITY?

**Comment by alexyo02** [comment] 2024-01-28 12:16
Hi, yes I can still pass BASIC integrity on all of the fp, searching on GitHub and Telegram I discovered that the problem is given by some custom kernels like LOS ones which I own, it seems the mainteiner of PlayIntegrityFix are working on a fix

**Comment by TheFreeman193** [comment] 2024-01-28 21:20
This may be your issue depending on the version naming of your ROM's kernel. You can check this in a root prompt with `uname -r`. If it has `lineageos` in the name or another of the keywords reported to be causing issues, that could be the cause.

**Comment by snowEdayz** [comment] 2024-02-02 06:08
I had this problem today, when the script asked me if this fingerprint was working, I went to check the play integrity and I didn't pass any integrity. When I force stopped Termux and checked again (same fingerprint), I passed the BASIC, DEVICE integrity.

**Comment by HarryTurney** [comment] 2024-02-12 19:43
I will also note my fingerprint stopped working today so I checked some from this list and I did run into a working one.

**Comment by aqtoo** [comment] 2024-03-03 02:34
I've been checking prints for an hour and no dice, CRDroid (ROM) Poco F3, am I just being extremely unlucky or is the kernel my issue?

**Comment by RedKage** [comment] 2024-03-03 06:56
I'm on a Poco F3, but on LineageOS.
I did have issues with safetynet as well but all is good now after an os update. 

Version 20.0-20240228 seems to have made some changes. Perhaps this commit "Allow signature spoofing for microG Companion/Services" did the trick https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383574

Here's my config of it can help

Magisk v27.0
- MagiskHide props config v6.1.2-v137
- Shamiko 1.0.1 (300)
- universal safetynet fix v2.4.0-mod-1.3-microG
- zygisk LSPosed 1.9.1 (6990)
- zygisk sui 13.5.1
- don't enforce deny list so shamiko can do it
- add to deny list the apps you want to hide
- configured props with the built in fingerprint for the poco f3, didn't force basic attestation

Lsposed
- BootLoaderSpoofed 3.8

For yasnac it was working fine without BootloaderSpoofed
For keyattestation I needed BootloaderSpoofed to have it pass the checks

**Comment by aqtoo** [comment] 2024-03-03 11:34
I'm using KSU so most of those checks wouldn't help me, (unless I'm stupid) should I try using BootloaderSpoofed to see if that helps?

I'm quite confused on some of these things.

**Comment by HarryTurney** [comment] 2024-03-03 12:14
Recently there was a big wave and someone said they checked every key and none were working.

Remember SafetyNet is deprecated and what matters now is PlayIntegrity

**Comment by aqtoo** [comment] 2024-03-03 12:19
> Recently there was a big wave and someone said they checked every key and none were working.
> 
> Remember SafetyNet is deprecated and what matters now is PlayIntegrity

I use Play Integrity V7 by Osm0sis, and I've tried many different keys from here with zero success, in the past I was able to get a few before Factory resetting my phone and it worked fine, unsure what changed.

**Comment by TheFreeman193** [comment] 2024-03-03 12:42
@HarryTurney @ac-tu @RedKage We've now tested over 7000 total device profiles/fingerprints that were previously passing device integrity, and the news is not good; 96% of those now fail after the leap day changes. That ratio applies to the PIFS collection too (which to reiterate is a random subset of publicly available build properties) and means the are only a handful left working.

None of those are for the most common ABI/architecture (`arm64-v8a,armeabi-v7a,armeabi`) which **effectively renders the collection useless** unless you're using an old x86/x86-64 device.

Sorry folks, but there's nothing more I can do. Google's apparent shift to outright hostility towards device modding means I can't in good faith publish the handful of prints that still work because they are likely to be blocked with even a moderate spike in usage.

**Comment by HarryTurney** [comment] 2024-03-03 12:55
Yeah, it sucks, rn I'm using the xiaomi-eu one but so are so many people so it's only time before that goes too.

**Comment by aqtoo** [comment] 2024-03-03 15:13
Oh my god. That's a insane amount of blocks, it's so bad to see google doing this :/

**Comment by TheFreeman193** [comment] 2024-03-03 22:08
As the kernel release string issue is now well-documented and moot in light of the recent blocks, I'm closing this issue. Best of luck everyone.

**Closed as completed by TheFreeman193** 2024-03-03 22:08 UTC
Labels: investigating, external bug
